/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PiRouteImport } from "./routes/pi"
import { Route as PtRouteImport } from "./routes/pt"
import { Route as VideoAgentRouteImport } from "./routes/video-agent"
import { Route as ApiPastedImagesRouteImport } from "./routes/api.pasted-images"
import { Route as CardsIndexRouteImport } from "./routes/cards.index"
import { Route as CardsIdRouteImport } from "./routes/cards.$id"
import { Route as CardsNewRouteImport } from "./routes/cards.new"
import { Route as DemoTableRouteImport } from "./routes/demo/table"
import { Route as DemoTanstackQueryRouteImport } from "./routes/demo/tanstack-query"
import { Route as PastedImagesNameRouteImport } from "./routes/pasted-images.$name"
import { Route as PastedTextsIdRouteImport } from "./routes/pasted-texts.$id"
import { Route as ApiTrpcSplatRouteImport } from "./routes/api.trpc.$"
import { Route as ApiVideoAgentUploadRouteImport } from "./routes/api.video-agent.upload"
import { Route as CardsIdEditRouteImport } from "./routes/cards.$id_.edit"
import { Route as DemoFormAddressRouteImport } from "./routes/demo/form.address"
import { Route as DemoFormSimpleRouteImport } from "./routes/demo/form.simple"
import { Route as ApiVideoAgentIdExportRouteImport } from "./routes/api.video-agent.$id.export"
import { Route as ApiVideoAgentIdVideoRouteImport } from "./routes/api.video-agent.$id.video"

const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
	id: "/pi",
	path: "/pi",
	getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
	id: "/pt",
	path: "/pt",
	getParentRoute: () => rootRouteImport,
} as any)
const VideoAgentRoute = VideoAgentRouteImport.update({
	id: "/video-agent",
	path: "/video-agent",
	getParentRoute: () => rootRouteImport,
} as any)
const ApiPastedImagesRoute = ApiPastedImagesRouteImport.update({
	id: "/api/pasted-images",
	path: "/api/pasted-images",
	getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
	id: "/cards/",
	path: "/cards/",
	getParentRoute: () => rootRouteImport,
} as any)
const CardsIdRoute = CardsIdRouteImport.update({
	id: "/cards/$id",
	path: "/cards/$id",
	getParentRoute: () => rootRouteImport,
} as any)
const CardsNewRoute = CardsNewRouteImport.update({
	id: "/cards/new",
	path: "/cards/new",
	getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
	id: "/demo/table",
	path: "/demo/table",
	getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
	id: "/demo/tanstack-query",
	path: "/demo/tanstack-query",
	getParentRoute: () => rootRouteImport,
} as any)
const PastedImagesNameRoute = PastedImagesNameRouteImport.update({
	id: "/pasted-images/$name",
	path: "/pasted-images/$name",
	getParentRoute: () => rootRouteImport,
} as any)
const PastedTextsIdRoute = PastedTextsIdRouteImport.update({
	id: "/pasted-texts/$id",
	path: "/pasted-texts/$id",
	getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
	id: "/api/trpc/$",
	path: "/api/trpc/$",
	getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentUploadRoute = ApiVideoAgentUploadRouteImport.update({
	id: "/api/video-agent/upload",
	path: "/api/video-agent/upload",
	getParentRoute: () => rootRouteImport,
} as any)
const CardsIdEditRoute = CardsIdEditRouteImport.update({
	id: "/cards/$id_/edit",
	path: "/cards/$id/edit",
	getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
	id: "/demo/form/address",
	path: "/demo/form/address",
	getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
	id: "/demo/form/simple",
	path: "/demo/form/simple",
	getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentIdExportRoute = ApiVideoAgentIdExportRouteImport.update({
	id: "/api/video-agent/$id/export",
	path: "/api/video-agent/$id/export",
	getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentIdVideoRoute = ApiVideoAgentIdVideoRouteImport.update({
	id: "/api/video-agent/$id/video",
	path: "/api/video-agent/$id/video",
	getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute
	"/pi": typeof PiRoute
	"/pt": typeof PtRoute
	"/video-agent": typeof VideoAgentRoute
	"/api/pasted-images": typeof ApiPastedImagesRoute
	"/cards/$id": typeof CardsIdRoute
	"/cards/new": typeof CardsNewRoute
	"/demo/table": typeof DemoTableRoute
	"/demo/tanstack-query": typeof DemoTanstackQueryRoute
	"/pasted-images/$name": typeof PastedImagesNameRoute
	"/pasted-texts/$id": typeof PastedTextsIdRoute
	"/cards/": typeof CardsIndexRoute
	"/api/trpc/$": typeof ApiTrpcSplatRoute
	"/api/video-agent/upload": typeof ApiVideoAgentUploadRoute
	"/cards/$id/edit": typeof CardsIdEditRoute
	"/demo/form/address": typeof DemoFormAddressRoute
	"/demo/form/simple": typeof DemoFormSimpleRoute
	"/api/video-agent/$id/export": typeof ApiVideoAgentIdExportRoute
	"/api/video-agent/$id/video": typeof ApiVideoAgentIdVideoRoute
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute
	"/pi": typeof PiRoute
	"/pt": typeof PtRoute
	"/video-agent": typeof VideoAgentRoute
	"/api/pasted-images": typeof ApiPastedImagesRoute
	"/cards/$id": typeof CardsIdRoute
	"/cards/new": typeof CardsNewRoute
	"/demo/table": typeof DemoTableRoute
	"/demo/tanstack-query": typeof DemoTanstackQueryRoute
	"/pasted-images/$name": typeof PastedImagesNameRoute
	"/pasted-texts/$id": typeof PastedTextsIdRoute
	"/cards": typeof CardsIndexRoute
	"/api/trpc/$": typeof ApiTrpcSplatRoute
	"/api/video-agent/upload": typeof ApiVideoAgentUploadRoute
	"/cards/$id/edit": typeof CardsIdEditRoute
	"/demo/form/address": typeof DemoFormAddressRoute
	"/demo/form/simple": typeof DemoFormSimpleRoute
	"/api/video-agent/$id/export": typeof ApiVideoAgentIdExportRoute
	"/api/video-agent/$id/video": typeof ApiVideoAgentIdVideoRoute
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport
	"/": typeof IndexRoute
	"/pi": typeof PiRoute
	"/pt": typeof PtRoute
	"/video-agent": typeof VideoAgentRoute
	"/api/pasted-images": typeof ApiPastedImagesRoute
	"/cards/$id": typeof CardsIdRoute
	"/cards/new": typeof CardsNewRoute
	"/demo/table": typeof DemoTableRoute
	"/demo/tanstack-query": typeof DemoTanstackQueryRoute
	"/pasted-images/$name": typeof PastedImagesNameRoute
	"/pasted-texts/$id": typeof PastedTextsIdRoute
	"/cards/": typeof CardsIndexRoute
	"/api/trpc/$": typeof ApiTrpcSplatRoute
	"/api/video-agent/upload": typeof ApiVideoAgentUploadRoute
	"/cards/$id_/edit": typeof CardsIdEditRoute
	"/demo/form/address": typeof DemoFormAddressRoute
	"/demo/form/simple": typeof DemoFormSimpleRoute
	"/api/video-agent/$id/export": typeof ApiVideoAgentIdExportRoute
	"/api/video-agent/$id/video": typeof ApiVideoAgentIdVideoRoute
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths:
		| "/"
		| "/pi"
		| "/pt"
		| "/video-agent"
		| "/api/pasted-images"
		| "/cards/$id"
		| "/cards/new"
		| "/demo/table"
		| "/demo/tanstack-query"
		| "/pasted-images/$name"
		| "/pasted-texts/$id"
		| "/cards/"
		| "/api/trpc/$"
		| "/api/video-agent/upload"
		| "/cards/$id/edit"
		| "/demo/form/address"
		| "/demo/form/simple"
		| "/api/video-agent/$id/export"
		| "/api/video-agent/$id/video"
	fileRoutesByTo: FileRoutesByTo
	to:
		| "/"
		| "/pi"
		| "/pt"
		| "/video-agent"
		| "/api/pasted-images"
		| "/cards/$id"
		| "/cards/new"
		| "/demo/table"
		| "/demo/tanstack-query"
		| "/pasted-images/$name"
		| "/pasted-texts/$id"
		| "/cards"
		| "/api/trpc/$"
		| "/api/video-agent/upload"
		| "/cards/$id/edit"
		| "/demo/form/address"
		| "/demo/form/simple"
		| "/api/video-agent/$id/export"
		| "/api/video-agent/$id/video"
	id:
		| "__root__"
		| "/"
		| "/pi"
		| "/pt"
		| "/video-agent"
		| "/api/pasted-images"
		| "/cards/$id"
		| "/cards/new"
		| "/demo/table"
		| "/demo/tanstack-query"
		| "/pasted-images/$name"
		| "/pasted-texts/$id"
		| "/cards/"
		| "/api/trpc/$"
		| "/api/video-agent/upload"
		| "/cards/$id_/edit"
		| "/demo/form/address"
		| "/demo/form/simple"
		| "/api/video-agent/$id/export"
		| "/api/video-agent/$id/video"
	fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	PiRoute: typeof PiRoute
	PtRoute: typeof PtRoute
	VideoAgentRoute: typeof VideoAgentRoute
	ApiPastedImagesRoute: typeof ApiPastedImagesRoute
	CardsIdRoute: typeof CardsIdRoute
	CardsNewRoute: typeof CardsNewRoute
	DemoTableRoute: typeof DemoTableRoute
	DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
	PastedImagesNameRoute: typeof PastedImagesNameRoute
	PastedTextsIdRoute: typeof PastedTextsIdRoute
	CardsIndexRoute: typeof CardsIndexRoute
	ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
	ApiVideoAgentUploadRoute: typeof ApiVideoAgentUploadRoute
	CardsIdEditRoute: typeof CardsIdEditRoute
	DemoFormAddressRoute: typeof DemoFormAddressRoute
	DemoFormSimpleRoute: typeof DemoFormSimpleRoute
	ApiVideoAgentIdExportRoute: typeof ApiVideoAgentIdExportRoute
	ApiVideoAgentIdVideoRoute: typeof ApiVideoAgentIdVideoRoute
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/"
			path: "/"
			fullPath: "/"
			preLoaderRoute: typeof IndexRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/pi": {
			id: "/pi"
			path: "/pi"
			fullPath: "/pi"
			preLoaderRoute: typeof PiRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/pt": {
			id: "/pt"
			path: "/pt"
			fullPath: "/pt"
			preLoaderRoute: typeof PtRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/video-agent": {
			id: "/video-agent"
			path: "/video-agent"
			fullPath: "/video-agent"
			preLoaderRoute: typeof VideoAgentRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/api/pasted-images": {
			id: "/api/pasted-images"
			path: "/api/pasted-images"
			fullPath: "/api/pasted-images"
			preLoaderRoute: typeof ApiPastedImagesRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/cards/": {
			id: "/cards/"
			path: "/cards"
			fullPath: "/cards/"
			preLoaderRoute: typeof CardsIndexRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/cards/$id": {
			id: "/cards/$id"
			path: "/cards/$id"
			fullPath: "/cards/$id"
			preLoaderRoute: typeof CardsIdRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/cards/new": {
			id: "/cards/new"
			path: "/cards/new"
			fullPath: "/cards/new"
			preLoaderRoute: typeof CardsNewRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/demo/table": {
			id: "/demo/table"
			path: "/demo/table"
			fullPath: "/demo/table"
			preLoaderRoute: typeof DemoTableRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/demo/tanstack-query": {
			id: "/demo/tanstack-query"
			path: "/demo/tanstack-query"
			fullPath: "/demo/tanstack-query"
			preLoaderRoute: typeof DemoTanstackQueryRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/pasted-images/$name": {
			id: "/pasted-images/$name"
			path: "/pasted-images/$name"
			fullPath: "/pasted-images/$name"
			preLoaderRoute: typeof PastedImagesNameRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/pasted-texts/$id": {
			id: "/pasted-texts/$id"
			path: "/pasted-texts/$id"
			fullPath: "/pasted-texts/$id"
			preLoaderRoute: typeof PastedTextsIdRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/api/trpc/$": {
			id: "/api/trpc/$"
			path: "/api/trpc/$"
			fullPath: "/api/trpc/$"
			preLoaderRoute: typeof ApiTrpcSplatRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/api/video-agent/upload": {
			id: "/api/video-agent/upload"
			path: "/api/video-agent/upload"
			fullPath: "/api/video-agent/upload"
			preLoaderRoute: typeof ApiVideoAgentUploadRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/cards/$id_/edit": {
			id: "/cards/$id_/edit"
			path: "/cards/$id/edit"
			fullPath: "/cards/$id/edit"
			preLoaderRoute: typeof CardsIdEditRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/demo/form/address": {
			id: "/demo/form/address"
			path: "/demo/form/address"
			fullPath: "/demo/form/address"
			preLoaderRoute: typeof DemoFormAddressRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/demo/form/simple": {
			id: "/demo/form/simple"
			path: "/demo/form/simple"
			fullPath: "/demo/form/simple"
			preLoaderRoute: typeof DemoFormSimpleRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/api/video-agent/$id/export": {
			id: "/api/video-agent/$id/export"
			path: "/api/video-agent/$id/export"
			fullPath: "/api/video-agent/$id/export"
			preLoaderRoute: typeof ApiVideoAgentIdExportRouteImport
			parentRoute: typeof rootRouteImport
		}
		"/api/video-agent/$id/video": {
			id: "/api/video-agent/$id/video"
			path: "/api/video-agent/$id/video"
			fullPath: "/api/video-agent/$id/video"
			preLoaderRoute: typeof ApiVideoAgentIdVideoRouteImport
			parentRoute: typeof rootRouteImport
		}
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	PiRoute: PiRoute,
	PtRoute: PtRoute,
	VideoAgentRoute: VideoAgentRoute,
	ApiPastedImagesRoute: ApiPastedImagesRoute,
	CardsIdRoute: CardsIdRoute,
	CardsNewRoute: CardsNewRoute,
	DemoTableRoute: DemoTableRoute,
	DemoTanstackQueryRoute: DemoTanstackQueryRoute,
	PastedImagesNameRoute: PastedImagesNameRoute,
	PastedTextsIdRoute: PastedTextsIdRoute,
	CardsIndexRoute: CardsIndexRoute,
	ApiTrpcSplatRoute: ApiTrpcSplatRoute,
	ApiVideoAgentUploadRoute: ApiVideoAgentUploadRoute,
	CardsIdEditRoute: CardsIdEditRoute,
	DemoFormAddressRoute: DemoFormAddressRoute,
	DemoFormSimpleRoute: DemoFormSimpleRoute,
	ApiVideoAgentIdExportRoute: ApiVideoAgentIdExportRoute,
	ApiVideoAgentIdVideoRoute: ApiVideoAgentIdVideoRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
	interface Register {
		ssr: true
		router: Awaited<ReturnType<typeof getRouter>>
	}
}
